### ISSUE TITLE
Can't install on node:lts-alpine

### ISSUE THREAD

**Issue by FezVrasta** [getsentry/profiling-node#247] opened 2024-09-17 15:40 UTC
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

8.30.0

### What environment is your node script running in?

Dockerfile with docker compose, it works on x86 machines but doesn't on my local MacBook M1 Max.

### How is your code deployed and bundled?

/

### Steps to Reproduce

```
$ npm install --verbose --foreground-scripts @sentry/profiling-node
npm verbose cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@10.8.2
npm info using node@v20.17.0
npm verbose title npm install @sentry/profiling-node
npm verbose argv "install" "--loglevel" "verbose" "--foreground-scripts" "@sentry/profiling-node"
npm verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-09-17T15_38_34_026Z-
npm verbose logfile /root/.npm/_logs/2024-09-17T15_38_34_026Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fprofiling-node 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc 154ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/node-abi 159ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2futils 208ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2ftypes 221ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fnode 240ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fcore 401ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-express 78ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi 90ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation 101ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fcontext-async-hooks 110ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fcore 116ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-connect 123ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-fastify 152ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-generic-pool 153ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-fs 156ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-hapi 69ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-graphql 91ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-ioredis 91ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-koa 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-http 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-mongodb 85ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-kafkajs 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-mongoose 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-mysql 94ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-nestjs-core 89ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-pg 82ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-mysql2 141ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/import-in-the-middle 54ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsdk-trace-base 100ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry%2fopentelemetry 91ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fresources 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-redis-4 146ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsemantic-conventions 122ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver 74ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation-undici 161ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@prisma%2finstrumentation 406ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/import-in-the-middle 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 15ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsemantic-conventions 21ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsemantic-conventions 16ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 12ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fconnect 65ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fshimmer 77ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi-logs 105ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/shimmer 108ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsdk-metrics 103ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fmysql 103ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/require-in-the-middle 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fredis-common 115ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2finstrumentation 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsql-common 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fpg 72ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fpg-pool 57ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fsql-common 105ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn-import-attributes 47ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fredis-common 86ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn 70ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/module-details-from-path 85ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/cjs-module-lexer 93ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/resolve 48ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/debug 52ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 360ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pg-protocol 51ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pg-types 59ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry%2fapi-logs 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/undici-types 58ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-array 58ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-date 79ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-bytea 80ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pg-int8 82ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-interval 119ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/xtend 36ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/supports-preserve-symlinks-flag 43ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-core-module 49ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/path-parse 59ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ms 60ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/hasown 61ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/function-bind 46ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz 115ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz 120ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/debug/-/debug-4.3.7.tgz 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.2.0.tgz 118ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.1.3.tgz 122ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/is-core-module/-/is-core-module-2.15.1.tgz 123ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz 127ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz 129ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pg-types/-/pg-types-2.2.0.tgz 145ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/cjs-module-lexer/-/cjs-module-lexer-1.4.1.tgz 154ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz 154ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/pg-pool/-/pg-pool-2.0.6.tgz 166ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/pg/-/pg-8.6.1.tgz 168ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/module-details-from-path/-/module-details-from-path-1.0.3.tgz 171ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.7.tgz 173ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn-import-attributes/-/acorn-import-attributes-1.9.5.tgz 174ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz 178ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/mysql/-/mysql-2.15.26.tgz 176ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/postgres-array/-/postgres-array-2.0.0.tgz 198ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/connect/-/connect-3.4.36.tgz 202ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz 210ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/undici-types/-/undici-types-6.19.8.tgz 212ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/acorn/-/acorn-8.12.1.tgz 215ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/shimmer/-/shimmer-1.2.1.tgz 212ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/require-in-the-middle/-/require-in-the-middle-7.4.0.tgz 215ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/shimmer/-/shimmer-1.2.0.tgz 217ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/pg-protocol/-/pg-protocol-1.7.0.tgz 225ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/redis-common/-/redis-common-0.36.2.tgz 232ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@prisma/instrumentation/-/instrumentation-5.19.1.tgz 237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/semver/-/semver-7.6.3.tgz 242ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/sql-common/-/sql-common-0.40.1.tgz 262ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-redis-4/-/instrumentation-redis-4-0.42.0.tgz 299ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/resolve/-/resolve-1.22.8.tgz 349ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-mysql/-/instrumentation-mysql-0.41.0.tgz 352ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-kafkajs/-/instrumentation-kafkajs-0.3.0.tgz 356ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-pg/-/instrumentation-pg-0.44.0.tgz 363ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-nestjs-core/-/instrumentation-nestjs-core-0.40.0.tgz 366ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-koa/-/instrumentation-koa-0.43.0.tgz 363ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-ioredis/-/instrumentation-ioredis-0.43.0.tgz 362ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-mongoose/-/instrumentation-mongoose-0.42.0.tgz 382ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-mysql2/-/instrumentation-mysql2-0.41.0.tgz 390ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/node-abi/-/node-abi-3.67.0.tgz 395ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-undici/-/instrumentation-undici-0.6.0.tgz 411ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/import-in-the-middle/-/import-in-the-middle-1.11.0.tgz 417ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-mongodb/-/instrumentation-mongodb-0.47.0.tgz 415ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.3.tgz 410ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-connect/-/instrumentation-connect-0.39.0.tgz 419ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-generic-pool/-/instrumentation-generic-pool-0.39.0.tgz 420ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/context-async-hooks/-/context-async-hooks-1.26.0.tgz 431ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-fs/-/instrumentation-fs-0.15.0.tgz 440ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-http/-/instrumentation-http-0.53.0.tgz 441ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-hapi/-/instrumentation-hapi-0.41.0.tgz 444ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-express/-/instrumentation-express-0.42.0.tgz 470ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-fastify/-/instrumentation-fastify-0.39.0.tgz 475ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@types/node/-/node-22.5.5.tgz 491ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation-graphql/-/instrumentation-graphql-0.43.0.tgz 478ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/opentelemetry/-/opentelemetry-8.30.0.tgz 581ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/api-logs/-/api-logs-0.53.0.tgz 629ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/types/-/types-8.30.0.tgz 715ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation/-/instrumentation-0.53.0.tgz 726ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/api-logs/-/api-logs-0.52.1.tgz 734ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/instrumentation/-/instrumentation-0.52.1.tgz 771ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/profiling-node/-/profiling-node-8.30.0.tgz 827ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/sdk-trace-base/-/sdk-trace-base-1.26.0.tgz 857ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/resources/-/resources-1.26.0.tgz 872ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/semantic-conventions/-/semantic-conventions-1.27.0.tgz 892ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/utils/-/utils-8.30.0.tgz 921ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/core/-/core-1.26.0.tgz 968ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/sdk-metrics/-/sdk-metrics-1.26.0.tgz 993ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/core/-/core-8.30.0.tgz 1017ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@opentelemetry/api/-/api-1.9.0.tgz 1031ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/@sentry/node/-/node-8.30.0.tgz 1030ms (cache miss)
npm info run @sentry/profiling-node@8.30.0 install node_modules/@sentry/profiling-node node scripts/check-build.js

> @sentry/profiling-node@8.30.0 install
> node scripts/check-build.js

@sentry/profiling-node: Precompiled binary found, attempting to load /tmp/node_modules/@sentry/profiling-node/lib/sentry_cpu_profiler-linux-arm64-musl-115.node
@sentry/profiling-node: Precompiled binary found, skipping build from source.
Segmentation fault
```

### Expected Result

/

### Actual Result

/

**Comment by JonasBa** [comment] 2024-09-17 15:49
Duplicate of https://github.com/getsentry/profiling-node/issues/247 (we migrated this repo to sentry js monorepo), a fix has been merged and this should be resolved with the next release

**Closed as completed by JonasBa** 2024-09-17 15:49 UTC

**Comment by FezVrasta** [comment] 2024-09-17 16:24
#247 is this issue 🤔

**Comment by JonasBa** [comment] 2024-09-17 17:03
Sorry, I meant https://github.com/getsentry/sentry-javascript/issues/12169
